eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    health-check-url: http://${spring.cloud.client.ipaddress}:${management.server.port}/actuator/health
    metadata-map:
      management:
        port: ${management.server.port}
  client:
    service-url:
      defaultZone: http://61.183.20.49:30001/eureka/

spring:
  datasource:
    url: jdbc:mysql://61.183.20.49:3307/xhb_dev?characterEncoding=UTF-8
    username: root
    password: KJXYxgbsite2017.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 2
      max-wait: 20000
      min-idel: 2

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml         