server:
  port: 40020


spring:
  application:
    name: siki-xhb-hello
  profiles:
    active: dev
  cloud:
    config:
      discovery:
        enable: false
      uri: http://192.168.1.2:30003
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
    bus:
      refresh:
        enabled: true