server:
  port: 30003

management:
  server:
    port: 39003
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: siki-springcloud-gateway
  cloud:
    gateway:
      routes:
      - id: ingredients
        uri: lb://siki-xhb-hello
        predicates:
        - Path=/hello.do
        filters:
        - name: Hystrix
          args:
            name: fetchIngredients
            fallbackUri: forward:/user.do
      - id: ingredients-fallback
        uri: http://localhost:40011
        predicates:
        - Path=/user.do
#      - id: add_request_parameter_route
#        uri: lb://siki-xhb-hello
#        predicates:
#        - Path=/**
#        filters:
#        - AddRequestParameter=foo, bar
#      - id: hystrix_route
#        uri: lb://siki-xhb-hello
#        predicates:
#        - Path=/hello.do
#        filters:
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/getUser.do
#      - id: add_request_header_route
#        uri: lb://siki-xhb-hello
#        filters:
#        - AddRequestHeader=X-Request-Foo, Bar
#      - id: remoteAddr_route_predicate_factory
#        uri: lb://siki-xhb-hello
#        order: 10000
#        predicates:
#         - RemoteAddr=127.0.0.1/24
#      - id: query_route_predicate_factory
#        uri: lb://siki-xhb-hello
#        order: 10000
#        predicates:
#          - Query=name, ab.
#      - id: path_route_predicate_factory
#        uri: lb://siki-xhb-hello
#        order: 10000
#        predicates:
#         - Path=/api/hello/v1/**
#        filters:
#         - StripPrefix=3
#      - id: method_route_predicate_factory
#        uri: lb://siki-xhb-hello
#        order: 10000
#        predicates:
#         - Method=GET
#      - id: host_route_predicate_factory
#        uri: lb://siki-xhb-hello
#        order: 10000
#        predicates:
#         - Host=**.test.com:30003
#       - id: header_route_predicate_factory
#         uri: lb://siki-xhb-hello
#         order: 10000
#         predicates:
#          - Header=X-Request-Id, \d+
#      - id: cookie_route_predicate_factory
#        uri: lb://siki-xhb-hello
#        order: 10001
#        predicates:
#          - Cookie=name, abc
#      - id: between_route_predicate_factory
#        uri: lb://siki-xhb-hello
#        order: 10000
#        predicates:
#         - Between=2019-08-16T15:50:00.789+08:00, 2019-08-16T15:56:00.789+08:00
#      - id: after_route_predicate_factory
#        uri: lb://siki-xhb-hello
#        order: 10000
#        predicates:
#         - After=2019-08-16T15:50:00.789+08:00
#      - id: before_route_predicate_factory
#        uri: lb://siki-xhb-hello
#        order: 10000
#        predicates:
#         - Before=2019-08-16T16:50:00.789+08:00

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    health-check-url: http://${spring.cloud.client.ipaddress}:${management.server.port}/actuator/health
    metadata-map:
      management:
        port: ${management.server.port}
  client:
    service-url:
      defaultZone: http://localhost:30001/eureka/