zuul:
  ignoreServices: '*'
  ignore-patterns: '/**/inner/**'
  addHostHeader: true
  routes:
    siki-xhb-user:
      path: /api/user/v1/**
      serviceId: siki-xhb-user
      sensitiveHeaders: user-agent,Cookie
    siki-xhb-msg:
      path: /api/msg/v1/**
      serviceId: siki-xhb-msg
      sensitiveHeaders: user-agent,Cookie
siki-xhb-msg:
  ribbon:
    ConnectTimeout: 250
    OkToRetryOnAllOperations: false
    ReadTimeout: 2000000       


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    health-check-url: http://${spring.cloud.client.ipaddress}:${management.server.port}/actuator/health
    metadata-map:
      management:
        port: ${management.server.port}
  client:
    service-url:
      defaultZone: http://192.168.37.129:30001/eureka/,http://192.168.37.131:30001/eureka/

spring:
  redis:
    database: 0
    host: 192.168.37.129
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 300
        max-idle: 8
        min-idle: 0     