server:
  port: 30009

management:
  server:
    port: 39009
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    preferIpAddress: true
    health-check-url: http://${spring.cloud.client.ipaddress}:${management.server.port}/actuator/health
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    metadata-map:
      management:
        port: ${management.server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:30001/eureka

spring:
  application:
    name: siki-xhb-zipkin-server

