server:
  port: 30001
management:
  server:
    port: 39001

spring:
  application:
    name: siki-xhb-eureka
  banner:
    location: classpath:config/banner.txt

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    health-check-url: http://${spring.cloud.client.ipaddress}:${management.server.port}/actuator/health
    metadata-map:
      management:
        port: ${management.server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:30001/eureka/


info:
  name: '@porject.artifactId@'
  version: '@project.version@'





