server:
  port: 30004

management:
  server:
    port: 39004
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    health-check-url: http://${spring.cloud.client.ipaddress}:${management.server.port}/actuator/health
    metadata-map:
      management:
        port: ${management.server.port}
  client:
    service-url:
      defaultZone: http://61.183.20.49:30001/eureka/

spring:
  application:
    name: '@artifactId@'
  banner:
    location: classpath:config/banner.txt
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jianggang1997/xhb-back.git
          search-paths: siki-xhb-config-repository/{application},{application}
          username: jianggang1997
          password: abc13797347245

info:
  name: siki-xhb-config
  version: '@project.version@'